// ─── Fallback Configuration ────────────────────────────────────────
// Used when Supabase is unavailable or tables haven't been seeded yet.
// Once the DB is populated, these are replaced by real data via merge.
// Extracted from GlobalEngineContext to keep the provider file focused.

import type { CurrencyConfig } from "@/app/actions/config";

// ─── Types ─────────────────────────────────────────────────────────
export type Locale = "en" | "fa";
export type Direction = "ltr" | "rtl";

// ─── Fallback Translation Dictionary ──────────────────────────────
export const fallbackTranslations: Record<Locale, Record<string, string>> = {
  en: {
    "global_demo.title": "Global Engine Demo",
    "global_demo.subtitle":
      "Centralized i18n, multi-currency & feature flag system",
    "global_demo.language": "Language",
    "global_demo.english": "English",
    "global_demo.persian": "فارسی",
    "global_demo.currency_title": "Multi-Currency Display",
    "global_demo.currency_desc":
      "Same value (500,000 minor units) formatted per country",
    "global_demo.usd_label": "United States (USD)",
    "global_demo.irr_label": "Iran (Toman)",
    "global_demo.feature_title": "Feature Flags",
    "global_demo.feature_desc":
      "Toggle features on/off — simulates per-country config",
    "global_demo.wallet": "Wallet",
    "global_demo.wallet_desc": "Your balance and transaction history",
    "global_demo.wallet_balance": "Wallet Balance",
    "global_demo.wallet_disabled": "Disabled in your country",
    "global_demo.dynamic_title": "Dynamic Layout Engine",
    "global_demo.dynamic_desc":
      "Components rendered from a JSON configuration array",
    "global_demo.header_card": "Welcome Back",
    "global_demo.header_card_desc": "Ready to crush your workout today?",
    "global_demo.stats_card": "Workout Stats",
    "global_demo.stats_card_desc": "Track your progress over time",
    "global_demo.stats_sets": "sets",
    "global_demo.stats_steps": "steps",
    "global_demo.stats_kcal": "kcal",
    "global_demo.toggle": "Toggle",
    "global_demo.enabled": "Enabled",
    "global_demo.disabled": "Disabled",
    "global_demo.minor_units": "Minor units (raw):",
    "login.title": "Welcome Back",
    "login.subtitle": "Sign in to continue",
    "login.phone_placeholder": "Phone Number",
    "login.otp_placeholder": "Verification Code",
    "login.button_send": "Send Code",
    "login.button_verify": "Verify",
    "login.button_resend": "Resend Code",
    "login.select_country": "Select Country",
    "login.otp_sent": "Code sent!",
    "login.invalid_otp": "Invalid code",
    "login.invalid_phone": "Invalid phone number",
    "login.verifying": "Verifying...",
    "login.sending": "Sending...",
    "login.back": "Back",
    "nav.home": "Home",
    "nav.explore": "Explore",
    "nav.workout": "Workout",
    "nav.community": "Community",
    "nav.bookings": "Bookings",
    "nav.profile": "Profile",
    "home.goodMorning": "Good Morning",
    "home.goodAfternoon": "Good Afternoon",
    "home.goodEvening": "Good Evening",
    "home.readyToTrain": "Ready to crush your workout today?",
    "home.walletBalance": "Wallet Balance",
    "home.topUp": "Top Up",
    "home.upcomingSession": "Upcoming Session",
    "home.explore": "Explore",
    "home.bookings": "Bookings",
    "home.favorites": "Favorites",
    "home.support": "Support",
    "home.popularGyms": "Popular Gyms",
    "home.viewAll": "View All",
    "home.session": "session",
    "explore.title": "Explore Gyms",
    "explore.search": "Search gyms...",
    "explore.filters": "Filters",
    "explore.sort": "Sort",
    "explore.sportTypes": "Sport Types",
    "explore.distance": "Distance",
    "explore.priceRange": "Price Range",
    "explore.rating": "Rating",
    "explore.amenities": "Amenities",
    "explore.sortNearest": "Nearest",
    "explore.sortCheapest": "Cheapest",
    "explore.sortHighestRated": "Highest Rated",
    "explore.sortMostPopular": "Most Popular",
    "explore.open": "Open",
    "explore.closed": "Closed",
    "explore.perSession": "per session",
    "explore.reviews": "reviews",
    "explore.noResults": "No gyms found",
    "explore.clearFilters": "Clear All",
    "explore.applyFilters": "Apply Filters",
    "explore.all": "All",
    "explore.km": "km",
    "explore.results": "results",
    "gymDetail.back": "Back",
    "gymDetail.photos": "Photos",
    "gymDetail.about": "About",
    "gymDetail.readMore": "Read More",
    "gymDetail.readLess": "Read Less",
    "gymDetail.workingHours": "Working Hours",
    "gymDetail.open": "Open Now",
    "gymDetail.closed": "Closed",
    "gymDetail.selectDate": "Select Date",
    "gymDetail.selectTime": "Select Time",
    "gymDetail.available": "Available",
    "gymDetail.full": "Full",
    "gymDetail.selected": "Selected",
    "gymDetail.trainers": "Trainers",
    "gymDetail.specialty": "Specialty",
    "gymDetail.amenities": "Amenities",
    "gymDetail.location": "Location",
    "gymDetail.getDirections": "Get Directions",
    "gymDetail.contact": "Contact",
    "gymDetail.phone": "Phone",
    "gymDetail.instagram": "Instagram",
    "gymDetail.website": "Website",
    "gymDetail.reviews": "Reviews",
    "gymDetail.writeReview": "Write a Review",
    "gymDetail.noReviews": "No reviews yet",
    "gymDetail.ratingSummary": "Rating Summary",
    "gymDetail.buySession": "Buy Session",
    "gymDetail.perSession": "per session",
    "gymDetail.sessionsLeft": "sessions left",
    "gymDetail.today": "Today",
    "gymDetail.tomorrow": "Tomorrow",
    "gymDetail.noSlots": "No available slots for this date",
    "booking.title": "Booking Summary",
    "booking.gym": "Gym",
    "booking.date": "Date",
    "booking.time": "Time",
    "booking.price": "Session Price",
    "booking.walletBalance": "Wallet Balance",
    "booking.balanceAfter": "Balance After",
    "booking.confirm": "Confirm Booking",
    "booking.cancel": "Cancel",
    "booking.success": "Booking Confirmed!",
    "booking.successDesc": "Your session has been booked successfully",
    "booking.viewBookings": "View My Bookings",
    "booking.backToGym": "Back to Gym",
    "booking.insufficientBalance": "Insufficient Balance",
    "booking.insufficientDesc":
      "You don't have enough balance to book this session",
    "booking.topUp": "Top Up Wallet",
    "booking.processing": "Processing...",
    "bookings.title": "My Bookings",
    "bookings.upcoming": "Upcoming",
    "bookings.completed": "Completed",
    "bookings.cancelled": "Cancelled",
    "bookings.empty": "No bookings yet",
    "bookings.emptyDesc": "When you book a session, it will appear here",
    "bookings.session": "Session",
    "bookings.rateReview": "Rate & Review",
    "bookings.cancelBooking": "Cancel Booking",
    "bookings.viewGym": "View Gym",
    "bookings.reviewTitle": "Rate Your Experience",
    "bookings.reviewDesc": "How was your session at this gym?",
    "bookings.submitReview": "Submit Review",
    "bookings.writeComment": "Write a comment...",
    "bookings.cancelledLabel": "Cancelled",
    "bookings.completedLabel": "Completed",
    "bookings.upcomingLabel": "Upcoming",
    "bookings.activeLabel": "Active",
    "bookings.expiredLabel": "Expired",
    "bookings.activeTab": "Active",
    "bookings.loading": "Loading bookings...",
    "bookings.showTicket": "Show Ticket",
    "bookings.ticketTitle": "Entry Pass",
    "bookings.checkInCode": "Check-in Code",
    "bookings.ticketNote": "Show this QR code at the gym entrance",
    "bookings.rebook": "Rebook",
    "booking.close": "Close",
    "profile.title": "Profile",
    "profile.editProfile": "Edit Profile",
    "profile.wallet": "Wallet",
    "profile.balance": "Balance",
    "profile.transactions": "Transactions",
    "profile.topUp": "Top Up",
    "profile.language": "Language",
    "profile.notifications": "Notifications",
    "profile.favorites": "Favorites",
    "profile.support": "Support",
    "profile.about": "About",
    "profile.logout": "Log Out",
    "profile.logoutConfirm": "Are you sure you want to log out?",
    "profile.sessions": "Sessions",
    "profile.memberSince": "Member since",
    "profile.save": "Save",
    "profile.cancel": "Cancel",
    "profile.editName": "Edit Name",
    "profile.namePlaceholder": "Enter your name",
    "profile.topUpTitle": "Top Up Wallet",
    "profile.topUpAmount": "Amount",
    "profile.topUpDesc":
      "Select or enter an amount to add to your wallet",
    "profile.customAmount": "Custom amount",
    "profile.recentTransactions": "Recent Transactions",
    "profile.noTransactions": "No transactions yet",
    "profile.deposit": "Deposit",
    "profile.withdrawal": "Withdrawal",
    "profile.payment": "Payment",
    "onboarding.title": "Let's Get Started",
    "onboarding.subtitle":
      "Tell us about yourself to personalize your experience",
    "onboarding.step1.title": "Personal Info",
    "onboarding.step1.subtitle": "What should we call you?",
    "onboarding.step1.name": "Full Name",
    "onboarding.step1.namePlaceholder": "Enter your name",
    "onboarding.step1.dob": "Date of Birth",
    "onboarding.step1.gender": "Gender",
    "onboarding.step1.male": "Male",
    "onboarding.step1.female": "Female",
    "onboarding.step1.other": "Other",
    "onboarding.step2.title": "Fitness Profile",
    "onboarding.step2.subtitle": "Help us tailor your experience",
    "onboarding.step2.level": "Fitness Level",
    "onboarding.step2.beginner": "Beginner",
    "onboarding.step2.intermediate": "Intermediate",
    "onboarding.step2.advanced": "Advanced",
    "onboarding.step2.professional": "Professional",
    "onboarding.step2.goals": "What are your goals?",
    "onboarding.step2.weight_loss": "Weight Loss",
    "onboarding.step2.muscle_gain": "Muscle Gain",
    "onboarding.step2.endurance": "Endurance",
    "onboarding.step2.flexibility": "Flexibility",
    "onboarding.step2.general_fitness": "General Fitness",
    "onboarding.step3.title": "Choose Your Gym",
    "onboarding.step3.subtitle": "Pick your home gym (optional)",
    "onboarding.next": "Next",
    "onboarding.back": "Back",
    "onboarding.complete": "Get Started!",
    "onboarding.step": "Step",
    "onboarding.of": "of",
    "onboarding.saving": "Saving...",
  },
  fa: {
    "global_demo.title": "دموی موتور سراسری",
    "global_demo.subtitle": "سیستم مرکزی چندزبانه، چندارزی و پرچم ویژگی",
    "global_demo.language": "زبان",
    "global_demo.english": "English",
    "global_demo.persian": "فارسی",
    "global_demo.currency_title": "نمایش چندارزی",
    "global_demo.currency_desc":
      "همان مقدار (۵۰۰٬۰۰۰ واحد کوچک) قالب‌بندی شده بر اساس کشور",
    "global_demo.usd_label": "ایالات متحده (دلار)",
    "global_demo.irr_label": "ایران (تومان)",
    "global_demo.feature_title": "پرچم‌های ویژگی",
    "global_demo.feature_desc":
      "فعال/غیرفعال کردن ویژگی‌ها — شبیه‌سازی پیکربندی کشور",
    "global_demo.wallet": "کیف پول",
    "global_demo.wallet_desc": "موجودی و تاریخچه تراکنش‌های شما",
    "global_demo.wallet_balance": "موجودی کیف پول",
    "global_demo.wallet_disabled": "در کشور شما غیرفعال است",
    "global_demo.dynamic_title": "موتور چیدمان پویا",
    "global_demo.dynamic_desc": "کامپوننت‌ها از آرایه JSON رندر شده‌اند",
    "global_demo.header_card": "خوش آمدید",
    "global_demo.header_card_desc": "آماده‌اید امروز تمرین کنید؟",
    "global_demo.stats_card": "آمار تمرین",
    "global_demo.stats_card_desc": "پیشرفت خود را در طول زمان پیگیری کنید",
    "global_demo.stats_sets": "ست",
    "global_demo.stats_steps": "قدم",
    "global_demo.stats_kcal": "کیلوکالری",
    "global_demo.toggle": "تغییر وضعیت",
    "global_demo.enabled": "فعال",
    "global_demo.disabled": "غیرفعال",
    "global_demo.minor_units": "واحدهای کوچک (خام):",
    "login.title": "خوش آمدید",
    "login.subtitle": "برای ادامه وارد شوید",
    "login.phone_placeholder": "شماره موبایل",
    "login.otp_placeholder": "کد تأیید",
    "login.button_send": "ارسال کد",
    "login.button_verify": "تأیید",
    "login.button_resend": "ارسال مجدد",
    "login.select_country": "انتخاب کشور",
    "login.otp_sent": "کد ارسال شد!",
    "login.invalid_otp": "کد نامعتبر",
    "login.invalid_phone": "شماره موبایل نامعتبر",
    "login.verifying": "در حال تأیید...",
    "login.sending": "در حال ارسال...",
    "login.back": "بازگشت",
    "nav.home": "خانه",
    "nav.explore": "جستجو",
    "nav.workout": "تمرین",
    "nav.community": "انجمن",
    "nav.bookings": "رزروها",
    "nav.profile": "پروفایل",
    "home.goodMorning": "صبح بخیر",
    "home.goodAfternoon": "عصر بخیر",
    "home.goodEvening": "عصر بخیر",
    "home.readyToTrain": "آماده‌اید امروز تمرین کنید؟",
    "home.walletBalance": "موجودی کیف پول",
    "home.topUp": "شارژ",
    "home.upcomingSession": "جلسه بعدی",
    "home.explore": "جستجو",
    "home.bookings": "رزروها",
    "home.favorites": "علاقه‌مندی‌ها",
    "home.support": "پشتیبانی",
    "home.popularGyms": "باشگاه‌های محبوب",
    "home.viewAll": "مشاهده همه",
    "home.session": "جلسه",
    "explore.title": "جستجوی باشگاه",
    "explore.search": "جستجوی باشگاه...",
    "explore.filters": "فیلترها",
    "explore.sort": "مرتب‌سازی",
    "explore.sportTypes": "نوع ورزش",
    "explore.distance": "فاصله",
    "explore.priceRange": "محدوده قیمت",
    "explore.rating": "امتیاز",
    "explore.amenities": "امکانات",
    "explore.sortNearest": "نزدیک‌ترین",
    "explore.sortCheapest": "ارزان‌ترین",
    "explore.sortHighestRated": "بالاترین امتیاز",
    "explore.sortMostPopular": "محبوب‌ترین",
    "explore.open": "باز",
    "explore.closed": "بسته",
    "explore.perSession": "هر جلسه",
    "explore.reviews": "نظر",
    "explore.noResults": "باشگاهی یافت نشد",
    "explore.clearFilters": "پاک کردن همه",
    "explore.applyFilters": "اعمال فیلترها",
    "explore.all": "همه",
    "explore.km": "کیلومتر",
    "explore.results": "نتیجه",
    "gymDetail.back": "بازگشت",
    "gymDetail.photos": "تصاویر",
    "gymDetail.about": "درباره باشگاه",
    "gymDetail.readMore": "بیشتر بخوانید",
    "gymDetail.readLess": "بستن",
    "gymDetail.workingHours": "ساعت کاری",
    "gymDetail.open": "باز است",
    "gymDetail.closed": "بسته",
    "gymDetail.selectDate": "انتخاب تاریخ",
    "gymDetail.selectTime": "انتخاب ساعت",
    "gymDetail.available": "آزاد",
    "gymDetail.full": "تکمیل",
    "gymDetail.selected": "انتخاب شده",
    "gymDetail.trainers": "مربی‌ها",
    "gymDetail.specialty": "تخصص",
    "gymDetail.amenities": "امکانات",
    "gymDetail.location": "موقعیت",
    "gymDetail.getDirections": "مسیریابی",
    "gymDetail.contact": "تماس",
    "gymDetail.phone": "تلفن",
    "gymDetail.instagram": "اینستاگرام",
    "gymDetail.website": "وبسایت",
    "gymDetail.reviews": "نظرات",
    "gymDetail.writeReview": "ثبت نظر",
    "gymDetail.noReviews": "هنوز نظری ثبت نشده",
    "gymDetail.ratingSummary": "خلاصه امتیازات",
    "gymDetail.buySession": "خرید جلسه",
    "gymDetail.perSession": "هر جلسه",
    "gymDetail.sessionsLeft": "جلسه باقی‌مانده",
    "gymDetail.today": "امروز",
    "gymDetail.tomorrow": "فردا",
    "gymDetail.noSlots": "ساعتی برای این تاریخ موجود نیست",
    "booking.title": "خلاصه رزرو",
    "booking.gym": "باشگاه",
    "booking.date": "تاریخ",
    "booking.time": "ساعت",
    "booking.price": "قیمت جلسه",
    "booking.walletBalance": "موجودی کیف پول",
    "booking.balanceAfter": "موجودی بعد از خرید",
    "booking.confirm": "تأیید رزرو",
    "booking.cancel": "انصراف",
    "booking.success": "رزرو تأیید شد!",
    "booking.successDesc": "جلسه شما با موفقیت رزرو شد",
    "booking.viewBookings": "مشاهده رزروها",
    "booking.backToGym": "بازگشت به باشگاه",
    "booking.insufficientBalance": "موجودی ناکافی",
    "booking.insufficientDesc":
      "موجودی کیف پول شما برای رزرو این جلسه کافی نیست",
    "booking.topUp": "شارژ کیف پول",
    "booking.processing": "در حال پردازش...",
    "bookings.title": "رزروهای من",
    "bookings.upcoming": "آینده",
    "bookings.completed": "تکمیل شده",
    "bookings.cancelled": "لغو شده",
    "bookings.empty": "هنوز رزروی ندارید",
    "bookings.emptyDesc": "وقتی جلسه‌ای رزرو کنید، اینجا نمایش داده می‌شود",
    "bookings.session": "جلسه",
    "bookings.rateReview": "امتیاز و نظر",
    "bookings.cancelBooking": "لغو رزرو",
    "bookings.viewGym": "مشاهده باشگاه",
    "bookings.reviewTitle": "تجربه خود را امتیاز دهید",
    "bookings.reviewDesc": "جلسه شما در این باشگاه چطور بود؟",
    "bookings.submitReview": "ثبت نظر",
    "bookings.writeComment": "نظر خود را بنویسید...",
    "bookings.cancelledLabel": "لغو شده",
    "bookings.completedLabel": "تکمیل شده",
    "bookings.upcomingLabel": "آینده",
    "bookings.activeLabel": "فعال",
    "bookings.expiredLabel": "منقضی شده",
    "bookings.activeTab": "فعال",
    "bookings.loading": "در حال بارگذاری...",
    "bookings.showTicket": "نمایش بلیط",
    "bookings.ticketTitle": "بلیط ورود",
    "bookings.checkInCode": "کد ورود",
    "bookings.ticketNote": "این کد QR را در ورودی باشگاه نشان دهید",
    "bookings.rebook": "رزرو مجدد",
    "booking.close": "بستن",
    "profile.title": "پروفایل",
    "profile.editProfile": "ویرایش پروفایل",
    "profile.wallet": "کیف پول",
    "profile.balance": "موجودی",
    "profile.transactions": "تراکنش‌ها",
    "profile.topUp": "شارژ",
    "profile.language": "زبان",
    "profile.notifications": "اعلان‌ها",
    "profile.favorites": "علاقه‌مندی‌ها",
    "profile.support": "پشتیبانی",
    "profile.about": "درباره ما",
    "profile.logout": "خروج",
    "profile.logoutConfirm": "آیا مطمئن هستید که می‌خواهید خارج شوید؟",
    "profile.sessions": "جلسات",
    "profile.memberSince": "عضو از",
    "profile.save": "ذخیره",
    "profile.cancel": "انصراف",
    "profile.editName": "ویرایش نام",
    "profile.namePlaceholder": "نام خود را وارد کنید",
    "profile.topUpTitle": "شارژ کیف پول",
    "profile.topUpAmount": "مبلغ",
    "profile.topUpDesc": "مبلغ مورد نظر برای شارژ را انتخاب یا وارد کنید",
    "profile.customAmount": "مبلغ دلخواه",
    "profile.recentTransactions": "تراکنش‌های اخیر",
    "profile.noTransactions": "هنوز تراکنشی ندارید",
    "profile.deposit": "واریز",
    "profile.withdrawal": "برداشت",
    "profile.payment": "پرداخت",
    "onboarding.title": "شروع کنیم",
    "onboarding.subtitle": "درباره خودتان بگویید تا تجربه شما شخصی‌سازی شود",
    "onboarding.step1.title": "اطلاعات شخصی",
    "onboarding.step1.subtitle": "چطور صدا کنیم؟",
    "onboarding.step1.name": "نام کامل",
    "onboarding.step1.namePlaceholder": "نام خود را وارد کنید",
    "onboarding.step1.dob": "تاریخ تولد",
    "onboarding.step1.gender": "جنسیت",
    "onboarding.step1.male": "مرد",
    "onboarding.step1.female": "زن",
    "onboarding.step1.other": "سایر",
    "onboarding.step2.title": "پروفایل ورزشی",
    "onboarding.step2.subtitle": "به ما کمک کنید تجربه شما را تنظیم کنیم",
    "onboarding.step2.level": "سطح ورزشی",
    "onboarding.step2.beginner": "مبتدی",
    "onboarding.step2.intermediate": "متوسط",
    "onboarding.step2.advanced": "پیشرفته",
    "onboarding.step2.professional": "حرفه‌ای",
    "onboarding.step2.goals": "هدف‌های شما چیست؟",
    "onboarding.step2.weight_loss": "کاهش وزن",
    "onboarding.step2.muscle_gain": "عضله‌سازی",
    "onboarding.step2.endurance": "استقامت",
    "onboarding.step2.flexibility": "انعطاف‌پذیری",
    "onboarding.step2.general_fitness": "تناسب عمومی",
    "onboarding.step3.title": "باشگاه خود را انتخاب کنید",
    "onboarding.step3.subtitle": "انتخاب باشگاه (اختیاری)",
    "onboarding.next": "بعدی",
    "onboarding.back": "قبلی",
    "onboarding.complete": "شروع!",
    "onboarding.step": "مرحله",
    "onboarding.of": "از",
    "onboarding.saving": "در حال ذخیره...",
  },
};

// ─── Fallback Currency Config ─────────────────────────────────────
export const fallbackCurrencyConfigs: Record<string, CurrencyConfig> = {
  US: {
    country_id: "US",
    currency_code: "USD",
    symbol: "$",
    locale: "en-US",
    decimals: 2,
    is_rtl: false,
  },
  IR: {
    country_id: "IR",
    currency_code: "IRR",
    symbol: "تومان",
    locale: "fa-IR",
    decimals: 0,
    is_rtl: true,
    display_unit: "تومان",
    unit_divisor: 10,
  },
  AE: {
    country_id: "AE",
    currency_code: "AED",
    symbol: "د.إ",
    locale: "ar-AE",
    decimals: 2,
    is_rtl: true,
  },
  TR: {
    country_id: "TR",
    currency_code: "TRY",
    symbol: "₺",
    locale: "tr-TR",
    decimals: 2,
    is_rtl: false,
  },
};

// ─── Fallback Feature Flags ───────────────────────────────────────
export const fallbackFeatureFlags: Record<string, boolean> = {
  wallet: true,
  social_feed: false,
  premium_coaching: false,
  booking_ticket: true,
};

// ─── Fallback RTL Map ─────────────────────────────────────────────
export const fallbackRtlMap: Record<Locale, boolean> = {
  en: false,
  fa: true,
};